apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: marxist-sloth-python 
  janus-idp.io/tekton: marxist-sloth-python
  backstage.io/kubernetes-id: marxist-sloth-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: marxist-sloth-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  