apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: marxist-sloth-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: marxist-sloth-python 
  name: marxist-sloth-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: marxist-sloth-python 
